export const DISPLAY_ALERT = 'Something is wrong'
export const CLOSE_ALERT = 'CLOSE_ALERT'
export const EMPTY_FIELDS = 'EMPTY_FIELDS'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';

export const CREATE_PROPERTY_BEGIN = 'CREATE_PROPERTY_BEGIN';
export const CREATE_PROPERTY_SUCCESS = 'CREATE_PROPERTY_SUCCESS';
export const CREATE_PROPERTY_ERROR = 'CREATE_PROPERTY_ERROR';

export const GET_PROPERTIES_BEGIN = 'GET_PROPERTIES_BEGIN';
export const GET_PROPERTIES_SUCCESS = 'GET_PROPERTIES_SUCCESS';

export const SET_EDIT_PROPERTY = 'SET_EDIT_PROPERTY';

export const DELETE_PROPERTY_BEGIN = "DELETE_PROPERTY_BEGIN";
export const DELETE_PROPERTY_SUCCESS = "DELETE_PROPERTY_SUCCESS";

export const EDIT_PROPERTY_BEGIN = 'EDIT_PROPERTY_BEGIN';
export const EDIT_PROPERTY_SUCCESS = 'EDIT_PROPERTY_SUCCESS';
export const EDIT_PROPERTY_ERROR = 'EDIT_PROPERTY_ERROR';

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN';
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS';

export const SEARCH_FILTER_CHANGE = 'SEARCH_FILTER_CHANGE';
export const RESET_FILTERS = 'RESET_FILTERS';

export const CHANGE_PAGE = 'CHANGE_PAGE';

export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';